<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <title>Transport Order Confirmation </title>
    <style>
        @page {
            margin: 90px 25px;
            font-family: sans-serif;
        }

        body {
            margin-top: 50px;
            padding: 10px;
        }

        header {
            position: fixed;
            top: -70px;
            left: 0px;
            right: 0px;
            height: 70px;
            line-height: 15px;
        }

        footer {
            position: fixed;
            bottom: -60px;
            left: 0;
            right: 0;
            height: 30px;
            font-size: 12px;
            background-color: #0f0f0f;
            color: white;
            line-height: 25px;
        }

        .page_num:before {
            content: counter(page);
        }

        .table_heading {
            font-size: 13px;
            font-weight: bold;
            margin-bottom: 3px;
            padding-bottom: 3px;
        }

        .table_row_heading {
            font-size: 11px;
            font-weight: bold;
        }

        .table_row_value {
            font-size: 11px;
        }

        table, th, td {
            border: 0px solid black;
            border-collapse: collapse;
        }

        .table_sections {
            border: 1px solid black;
            border-collapse: collapse;
        }

        th, td {
            padding: 3px;
        }

        .section_heading {
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 1px;
            padding-bottom: 2px;
            margin-top: 2px;
        }

        .page-break {
            page-break-after: always;
        }


    </style>
</head>
<body>
<!-- Define header and footer blocks before your content -->
<header>
    <table style="width:100%">
        <tr>
            <td>
                <img style="float: left" src="{{ $logo }}" width="235" height="110"/>
            </td>
            <td style="float: right; text-align: right; font-size: 12px"><span><br><br>P.O. Box 71658, Rink Street<br>Port Elizabeth, 6001<br>Tel : +27 82 897 5966<br>+27 41 582 1952<br>Email : <a>documents@silvergro.co.za</a></span><br><br>
            </td>
        </tr>

    </table>

</header>

<footer>
    <div style="text-align: center">
        <span>SilverGro Feed & Grain</span>
        <span>| Generated by {{$user_name}}</span>
        <span>on {{$now}}</span>
        <span>| version {{$app_version}}</span>
        <span>| Page: </span> <span class="page_num"> </span>

    </div>
</footer>

<!-- Wrap the content of your PDF inside a main tag -->
<main>
    <div style="">

        <div style="margin-top: 5px;">
            <table style="width:100%">
                <tr>
                    <td></td>
                    <td style="float: right; text-align: right; font-size: 20px;">
                        <b><span>Transport Order Confirmation:</span> <span>TOC</span>
                            <span>{{$transport_trans->id}}</span>
                        </b>
                    </td>

                </tr>

                <tr>
                    <td></td>
                    <td style="float: right; text-align: right; font-size: 14px">
                        @if($final_transport_order)
                            <span>Final Version</span>

                        @else
                            <span style="color:red">Working Document Version</span>
                        @endif

                    </td>
                </tr>

            </table>

            <ol type="1">
                @if($transport_trans->is_split_load)
                    <h4>SPLIT LOAD DEAL</h4>
                @endif

                <li class="section_heading">Transporter Details</li>
                <div>
                    <table class="table_sections" style="width:100%;">
                        <tbody>
                        <tr class="table_sections">
                            <td class="table_sections table_row_heading">Transporter</td>
                            <td class="table_sections table_row_value"
                                colspan="3">{{$transport_trans->Transporter->last_legal_name}}</td>
                        </tr>
                        <tr class="table_sections">
                            <td class="table_sections table_row_heading">Transporter contact:</td>
                            <td class="table_sections table_row_value"
                                colspan="3"></td>
                        </tr>

                        </tbody>

                    </table>

                </div>
                <br>
                <li class="section_heading">Product & Tariff Detail</li>
                <div>
                    <table class="table_sections" style="width:100%;">
                        <tbody>
                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Product</td>
                            <td class="table_sections table_row_value">{{$transport_trans->product->name}}</td>
                            <td class="table_sections table_row_heading">Grade</td>
                            <td class="table_sections table_row_value">{{$transport_trans->TransportLoad->product_grade_perc}}</td>
                        </tr>

                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Source</td>
                            <td class="table_sections table_row_value">{{$transport_trans->TransportLoad->ProductSource->name}}</td>
                            <td class="table_sections table_row_heading">Package outgoing</td>
                            <td class="table_sections table_row_value">{{$transport_trans->TransportLoad->PackagingOutgoing->name}}</td>
                        </tr>

                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Transport Rate Basis</td>
                            <td class="table_sections table_row_value">{{$transport_trans->TransportFinance->TransportRateBasis->name}}</td>
                            <td class="table_sections table_row_heading">Load Rate / Ton</td>
                            <td class="table_sections table_row_value">
                                R {{number_format(round($transport_trans->TransportFinance->transport_rate_per_ton,2), 2, '.', ' ')}}
                            </td>
                        </tr>

                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Load Insurance / Ton</td>
                            <td class="table_sections table_row_value">
                                R {{number_format(round($transport_trans->TransportFinance->load_insurance_per_ton,2), 2, '.', ' ')}}
                            </td>
                            <td class="table_sections table_row_heading">Confirmed By</td>
                            <td class="table_sections table_row_value">
                                {{$transport_order->ConfirmedByType->name}}
                            </td>
                        </tr>

                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Terms of payment</td>
                            <td class="table_sections table_row_value">
                                {{$transport_trans->Transporter->TermsOfPayment->value}}
                            </td>
                            <td class="table_sections table_row_heading"></td>
                            <td class="table_sections table_row_value">

                            </td>
                        </tr>


                        </tbody>

                    </table>
                </div>
                <br>
                <li class="section_heading">Transport Details</li>
                <div>
                    <table class="table_sections" style="width:100%;">
                        <tbody>
                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Transport Date Earliest
                            </td>
                            <td class="table_sections table_row_value">{{$transport_trans->transport_date_earliest}}</td>
                            <td class="table_sections table_row_heading">Collection from</td>
                            <td class="table_sections table_row_value">{{$transport_trans->TransportJob->LoadingHoursFrom->name}}
                                <
                            </td>
                        </tr>

                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Transport Date Latest</td>
                            <td class="table_sections table_row_value">{{$transport_trans->transport_date_latest}}</td>
                            <td class="table_sections table_row_heading">Collection to</td>
                            <td class="table_sections table_row_value">{{$transport_trans->TransportJob->LoadingHoursTo->name}}</td>
                        </tr>

                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">No. Of Loads</td>
                            <td class="table_sections table_row_value">{{$transport_trans->TransportJob->number_loads}}</td>
                            <td class="table_sections table_row_heading">Vehicle details</td>
                            <td class="table_sections table_row_value">

                                @foreach($transport_trans->TransportJob->TransportDriverVehicle as $driver_vehicle)
                                    <p style="font-weight: bold;">Driver vehicle:</p>
                                    <p>
                                        <span>Driver:</span>
                                        <span> {{$driver_vehicle->Driver->first_name}} {{$driver_vehicle->Driver->last_name}}</span>
                                    </p>

                                    <p>
                                        <span>Cell: </span>
                                        <span> {{$driver_vehicle->Driver->cell_no}}</span>
                                    </p>

                                    <p> <span>Vehicle Reg: </span> <span>{{$driver_vehicle->Vehicle->reg_no}}  </span> </p>
                                    <p><span>Vehicle Type:</span> <span>{{$driver_vehicle->Vehicle->VehicleType->name}}</span></p>
                                    <p><span>Loading no:</span> <span>{{$driver_vehicle->driver_vehicle_loading_number}}</span></p>

                                @endforeach


                            </td>
                        </tr>


                        </tbody>

                    </table>
                </div>
                <br>
                <li class="section_heading">Loading & Offloading Detail</li>
                <div class="page-break">
                    <table class="table_sections" style="width:100%;">
                        <tbody>
                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Supplier name
                            </td>
                            <td class="table_sections table_row_value">{{$transport_trans->Supplier->last_legal_name}}</td>
                            <td class="table_sections table_row_heading">Customer name</td>
                            <td class="table_sections table_row_value">{{$transport_trans->Customer->last_legal_name}}
                            </td>
                        </tr>

                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Supplier loading number
                            </td>
                            <td class="table_sections table_row_value">
                                {{$transport_trans->TransportJob->supplier_loading_number}}
                            </td>
                            <td class="table_sections table_row_heading">Customer order number</td>
                            <td class="table_sections table_row_value">{{$transport_trans->TransportJob->customer_order_number}}
                            </td>
                        </tr>


                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Collection Address</td>
                            <td class="table_sections table_row_value">
                                <span>{{$transport_trans->TransportLoad->CollectionAddress->line_1}}</span>
                                <br>
                                <span>
                                    {{$transport_trans->TransportLoad->CollectionAddress->line_2}}
                                </span>
                                <br>
                                <span>
                                    {{$transport_trans->TransportLoad->CollectionAddress->line_3}}
                                </span>
                                <br>
                                <span>{{$transport_trans->TransportLoad->CollectionAddress->country}}</span>
                                <br>
                                <span>{{$transport_trans->TransportLoad->CollectionAddress->code}}</span>

                            </td>
                            <td class="table_sections table_row_heading">Delivery Address</td>
                            <td class="table_sections table_row_value">
                                <span>{{$transport_trans->TransportLoad->DeliveryAddress->line_1}}</span>
                                <br>
                                <span>
                                    {{$transport_trans->TransportLoad->DeliveryAddress->line_2}}
                                </span>
                                <br>
                                <span>
                                    {{$transport_trans->TransportLoad->DeliveryAddress->line_3}}
                                </span>
                                <br>
                                <span>{{$transport_trans->TransportLoad->DeliveryAddress->country}}</span>
                                <br>
                                <span>{{$transport_trans->TransportLoad->DeliveryAddress->code}}</span>
                            </td>
                        </tr>

                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Loading instructions
                            </td>
                            <td class="table_sections table_row_value">{{$transport_trans->TransportJob->loading_instructions}}</td>
                            <td class="table_sections table_row_heading">Offloading instructions</td>
                            <td class="table_sections table_row_value">{{$transport_trans->TransportJob->offloading_instructions}}
                            </td>
                        </tr>

                        <tr class="table_sections">
                            <td class="table_sections table_row_heading" style="width: 20%;">Supplier contact:
                            </td>
                            <td class="table_sections table_row_value"></td>
                            <td class="table_sections table_row_heading">Customer contact:</td>
                            <td class="table_sections table_row_value">
                            </td>
                        </tr>


                        </tbody>

                    </table>
                </div>
                    @if($transport_trans->is_split_load)
                        <li class="section_heading">Split Load Details</li>
                        @if($transport_trans->Customer_2->last_legal_name != 'Unallocated')
                            <div>
                                <table class="table_sections" style="width:100%;">
                                    <tbody>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading">Split Customer 2</td>
                                        <td class="table_sections table_row_value"
                                            colspan="3">{{$transport_trans->Customer_2->last_legal_name}}</td>
                                    </tr>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Collection Address</td>
                                        <td class="table_sections table_row_value">
                                    <span>
                                        {{$transport_trans->TransportLoad->CollectionAddress->line_1}}</span>
                                            <br>
                                            <span>
                                    {{$transport_trans->TransportLoad->CollectionAddress->line_2}}
                                </span>
                                            <br>
                                            <span>
                                    {{$transport_trans->TransportLoad->CollectionAddress->line_3}}
                                </span>
                                            <br>
                                            <span>{{$transport_trans->TransportLoad->CollectionAddress->country}}</span>
                                            <br>
                                            <span>{{$transport_trans->TransportLoad->CollectionAddress->code}}</span>

                                        </td>
                                        <td class="table_sections table_row_heading">Delivery Address</td>
                                        <td class="table_sections table_row_value">
                                    <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_2))
                                            {{$transport_trans->TransportLoad->DeliveryAddress_2->line_1}}
                                        @endif
                                    </span>
                                            <br>
                                            <span>
                                         @if(isset($transport_trans->TransportLoad->DeliveryAddress_2))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_2->line_2}}
                                                @endif
                                </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_2))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_2->line_3}}
                                                @endif
                                </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_2))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_2->country}}
                                                @endif

                                    </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_2))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_2->code}}
                                                @endif
                                    </span>
                                        </td>
                                    </tr>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Selling Price Split
                                        </td>
                                        <td class="table_sections table_row_value">
                                            R {{number_format(round($transport_trans->TransportFinance->selling_price_2,2), 2, '.', ' ')}}
                                        </td>
                                        <td class="table_sections table_row_heading">Transport Cost Split</td>
                                        <td class="table_sections table_row_value">
                                            R {{number_format(round($transport_trans->TransportFinance->transport_cost_2,2), 2, '.', ' ')}}
                                        </td>
                                    </tr>

                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Unit Split</td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportLoad->no_units_outgoing_2}}
                                        </td>
                                        <td class="table_sections table_row_heading">Customer order no</td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportJob->customer_order_number_2}}
                                        </td>
                                    </tr>

                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Supplier loading no
                                        </td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportJob->supplier_loading_number_2}}
                                        </td>
                                        <td class="table_sections table_row_heading"></td>
                                        <td class="table_sections table_row_value">

                                        </td>
                                    </tr>

                                    </tbody>

                                </table>
                            </div>
                            <br>
                        @endif
                        @if($transport_trans->Customer_3->last_legal_name != 'Unallocated')
                            <div>
                                <table class="table_sections" style="width:100%;">
                                    <tbody>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading">Split Customer 3</td>
                                        <td class="table_sections table_row_value"
                                            colspan="3">{{$transport_trans->Customer_3->last_legal_name}}</td>
                                    </tr>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Collection
                                            Address
                                        </td>
                                        <td class="table_sections table_row_value">
                                    <span>
                                        {{$transport_trans->TransportLoad->CollectionAddress->line_1}}</span>
                                            <br>
                                            <span>
                                    {{$transport_trans->TransportLoad->CollectionAddress->line_2}}
                                </span>
                                            <br>
                                            <span>
                                    {{$transport_trans->TransportLoad->CollectionAddress->line_3}}
                                </span>
                                            <br>
                                            <span>{{$transport_trans->TransportLoad->CollectionAddress->country}}</span>
                                            <br>
                                            <span>{{$transport_trans->TransportLoad->CollectionAddress->code}}</span>

                                        </td>
                                        <td class="table_sections table_row_heading">Delivery Address</td>
                                        <td class="table_sections table_row_value">
                                    <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_3))
                                            {{$transport_trans->TransportLoad->DeliveryAddress_3->line_1}}
                                        @endif
                                    </span>
                                            <br>
                                            <span>
                                         @if(isset($transport_trans->TransportLoad->DeliveryAddress_3))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_3->line_2}}
                                                @endif
                                </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_2))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress->line_3}}
                                                @endif
                                </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_2))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress->country}}
                                                @endif

                                    </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_2))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress->code}}
                                                @endif
                                    </span>
                                        </td>
                                    </tr>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Selling Price
                                            Split
                                        </td>
                                        <td class="table_sections table_row_value">
                                            R {{number_format(round($transport_trans->TransportFinance->selling_price_2,2), 2, '.', ' ')}}
                                        </td>
                                        <td class="table_sections table_row_heading">Transport Cost Split</td>
                                        <td class="table_sections table_row_value">
                                            R {{number_format(round($transport_trans->TransportFinance->transport_cost_2,2), 2, '.', ' ')}}
                                        </td>
                                    </tr>

                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Unit Split</td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportLoad->no_units_outgoing_2}}
                                        </td>
                                        <td class="table_sections table_row_heading">Customer order no</td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportJob->customer_order_number_2}}
                                        </td>
                                    </tr>

                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Supplier
                                            loading no
                                        </td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportJob->supplier_loading_number_2}}
                                        </td>
                                        <td class="table_sections table_row_heading"></td>
                                        <td class="table_sections table_row_value">

                                        </td>
                                    </tr>


                                    </tbody>

                                </table>
                            </div>
                            <br>
                        @endif
                        @if($transport_trans->Customer_4->last_legal_name != 'Unallocated')
                            <div>
                                <table class="table_sections" style="width:100%;">
                                    <tbody>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading">Split Customer 4</td>
                                        <td class="table_sections table_row_value"
                                            colspan="3">{{$transport_trans->Customer_4->last_legal_name}}</td>
                                    </tr>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Collection
                                            Address
                                        </td>
                                        <td class="table_sections table_row_value">
                                    <span>
                                        {{$transport_trans->TransportLoad->CollectionAddress->line_1}}</span>
                                            <br>
                                            <span>
                                    {{$transport_trans->TransportLoad->CollectionAddress->line_2}}
                                </span>
                                            <br>
                                            <span>
                                    {{$transport_trans->TransportLoad->CollectionAddress->line_3}}
                                </span>
                                            <br>
                                            <span>{{$transport_trans->TransportLoad->CollectionAddress->country}}</span>
                                            <br>
                                            <span>{{$transport_trans->TransportLoad->CollectionAddress->code}}</span>

                                        </td>
                                        <td class="table_sections table_row_heading">Delivery Address</td>
                                        <td class="table_sections table_row_value">
                                    <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_4))
                                            {{$transport_trans->TransportLoad->DeliveryAddress_4->line_1}}
                                        @endif
                                    </span>
                                            <br>
                                            <span>
                                         @if(isset($transport_trans->TransportLoad->DeliveryAddress_4))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_4->line_2}}
                                                @endif
                                </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_4))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_4->line_3}}
                                                @endif
                                </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_4))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_4->country}}
                                                @endif

                                    </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_4))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_4->code}}
                                                @endif
                                    </span>
                                        </td>
                                    </tr>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Selling Price
                                            Split
                                        </td>
                                        <td class="table_sections table_row_value">
                                            R {{number_format(round($transport_trans->TransportFinance->selling_price_4,2), 2, '.', ' ')}}
                                        </td>
                                        <td class="table_sections table_row_heading">Transport Cost Split</td>
                                        <td class="table_sections table_row_value">
                                            R {{number_format(round($transport_trans->TransportFinance->transport_cost_4,2), 2, '.', ' ')}}
                                        </td>
                                    </tr>

                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Unit Split</td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportLoad->no_units_outgoing_4}}
                                        </td>
                                        <td class="table_sections table_row_heading">Customer order no</td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportJob->customer_order_number_4}}
                                        </td>
                                    </tr>

                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Supplier
                                            loading no
                                        </td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportJob->supplier_loading_number_4}}
                                        </td>
                                        <td class="table_sections table_row_heading"></td>
                                        <td class="table_sections table_row_value">

                                        </td>
                                    </tr>


                                    </tbody>

                                </table>
                            </div>
                            <br>
                        @endif
                        @if($transport_trans->Customer_5->last_legal_name != 'Unallocated')
                            <div>
                                <table class="table_sections" style="width:100%;">
                                    <tbody>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading">Split Customer 5</td>
                                        <td class="table_sections table_row_value"
                                            colspan="3">{{$transport_trans->Customer_5->last_legal_name}}</td>
                                    </tr>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Collection
                                            Address
                                        </td>
                                        <td class="table_sections table_row_value">
                                    <span>
                                        {{$transport_trans->TransportLoad->CollectionAddress->line_1}}</span>
                                            <br>
                                            <span>
                                    {{$transport_trans->TransportLoad->CollectionAddress->line_2}}
                                </span>
                                            <br>
                                            <span>
                                    {{$transport_trans->TransportLoad->CollectionAddress->line_3}}
                                </span>
                                            <br>
                                            <span>{{$transport_trans->TransportLoad->CollectionAddress->country}}</span>
                                            <br>
                                            <span>{{$transport_trans->TransportLoad->CollectionAddress->code}}</span>

                                        </td>
                                        <td class="table_sections table_row_heading">Delivery Address</td>
                                        <td class="table_sections table_row_value">
                                    <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_5))
                                            {{$transport_trans->TransportLoad->DeliveryAddress_5->line_1}}
                                        @endif
                                    </span>
                                            <br>
                                            <span>
                                         @if(isset($transport_trans->TransportLoad->DeliveryAddress_5))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_5->line_2}}
                                                @endif
                                </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_5))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_5->line_3}}
                                                @endif
                                </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_5))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_5->country}}
                                                @endif

                                    </span>
                                            <br>
                                            <span>
                                        @if(isset($transport_trans->TransportLoad->DeliveryAddress_5))
                                                    {{$transport_trans->TransportLoad->DeliveryAddress_5->code}}
                                                @endif
                                    </span>
                                        </td>
                                    </tr>
                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Selling Price
                                            Split
                                        </td>
                                        <td class="table_sections table_row_value">
                                            R {{number_format(round($transport_trans->TransportFinance->selling_price_5,2), 2, '.', ' ')}}
                                        </td>
                                        <td class="table_sections table_row_heading">Transport Cost Split</td>
                                        <td class="table_sections table_row_value">
                                            R {{number_format(round($transport_trans->TransportFinance->transport_cost_5,2), 2, '.', ' ')}}
                                        </td>
                                    </tr>

                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Unit Split</td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportLoad->no_units_outgoing_5}}
                                        </td>
                                        <td class="table_sections table_row_heading">Customer order no</td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportJob->customer_order_number_5}}
                                        </td>
                                    </tr>

                                    <tr class="table_sections">
                                        <td class="table_sections table_row_heading" style="width: 20%;">Supplier
                                            loading no
                                        </td>
                                        <td class="table_sections table_row_value">
                                            {{$transport_trans->TransportJob->supplier_loading_number_5x}}
                                        </td>
                                        <td class="table_sections table_row_heading"></td>
                                        <td class="table_sections table_row_value">

                                        </td>
                                    </tr>


                                    </tbody>

                                </table>
                            </div>
                            <br>
                        @endif
                    @endif


                    <div class="table_row_value">
                    <ol>
                        <li>
                            Transport Rate:- The rate is valid for the completion of this transport order on the tonnage agreed upon.
                        </li>

                        <li>
                            Payment Terms:- will be made on receiving of transport's invoice with original documentation, normally within 14 working days from date of receipt of the original invoice/s,
                            and based on upload weight.
                        </li>

                        <li>
                            Original Documentation:- Payment will only be on receiving of the transporter's POD's, the original invoice with all original loading documentation as well as original
                            offloading documentation.
                        </li>

                        <li>
                            Load Insurance: The transporter confirms that the value of the load(s), calculated at the selling value of the commodity, that is R4,455.00 per mt, is fully insured by the
                            Transport Company / CC / Other for all possible risks.
                        </li>

                        <li>
                            Transporter to provide customer ONLY a delivery note with the following information: Supplier Name - SilverGro Feed and Grain, Customer Name as per the Transport Order,
                            Transport Order Number, The Product Description, Upload Weighbridge Weight and Weighbridge No, Truck Registration, Driver Name, Delivery Date, Delivery Time, Customer
                            Signature.
                        </li>

                        <li>
                            Contract Stipulations:- Please ensure you are familiar with SilverGro Feed & Grain's standard transport contract
                        </li>
                    </ol>
                </div>
                <br>
                <li class="section_heading">Signatures</li>
                <div>
                    <table class="" style="width:100%;">
                        <tbody>
                        <tr class="">
                            <td class=" table_row_value" style="width:25%;">
                                <br>
                                <br>
                                <br>
                                <hr>
                            </td>
                            <td class=" table_row_value" style="width:25%;">
                                <br>
                                <br>
                                <br>
                                <hr>
                            </td>
                            <td class=" table_row_value" style="width:25%;">
                                <br>
                                <br>
                                <br>
                                <hr>
                            </td>
                            <td class=" table_row_value" style="width:25%;">
                                <br>
                                <br>
                                <br>
                                <hr>
                            </td>
                        </tr>
                        <tr style="margin-top: 4px;">
                            <td class=" table_row_heading">Trader</td>
                            <td class=" table_row_heading">Trading Director</td>
                            <td class=" table_row_heading">Financial Director</td>
                            <td class=" table_row_heading">Transporter</td>
                        </tr>

                        </tbody>

                    </table>
                </div>

            </ol>


        </div>

    </div>
</main>
</body>
</html>
